version: "3.7"

services:
  payment:
    image: node:14-alpine3.11
    working_dir: /app
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: sh -c "npm i && npm run dev"
  mongoBdd:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
networks:
  micro-service:
    driver: bridge
